apiVersion: v1
kind: Secret
metadata:
  name: ts-domain-config-service-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL2RvbWFpbl9jb25maWdz
  SPRING_DATASOURCE_USERNAME: "cG9zdGdyZXM=" # postgres
  SPRING_DATASOURCE_PASSWORD: "cm9vdA=="     # root
